### ISSUE TITLE
time.c

### ISSUE THREAD

**Issue by Bruce9096** [AHR-Project/nmealib#18]
Hi there
I have add the nmea folder and the src folder to my project.
But I have faced two problems now, In the time.c file, 

firstly, the identifier"time_t" is not defined. 

secondly, for " stm->year = tt->tm_year;
    stm->mon = tt->tm_mon;
    stm->day = tt->tm_mday;
    stm->hour = tt->tm_hour;
    stm->min = tt->tm_min;
    stm->sec = tt->tm_sec;"
the build menu saied " the pointer to incomplete class type is not allowed"

coul you please help me for that, thankyou so much.

Linyu

**Comment by fhuberts** [comment]
OS? Compiler? etc.

Only Linux of currently supported

**Comment by fhuberts** [comment]
no response, closing
