### ISSUE TITLE
misuse of va_arg in util.c/nmeaScanf

### ISSUE THREAD

**Issue by nickds1** [AHR-Project/nmealib#20]
In all versions of nmealib, in the scanf utility function, a check is made for a NULL return from va_arg.

This is not a valid check for an extant argument, or indeed anything at all - va_arg has no way of knowing whether there are any arguments left - it just runs off the end of the list and returns whatever is there, which is generally some rubbish data from the stack.

This behavior is in the standards documents, and also in on-line references, e.g. at http://www.cplusplus.com/reference/cstdarg/va_arg/

The NULL test should be removed (it's not valid) and an alternative provided, e.g. an explicit argument count or, more easily, terminating the argument list with an explicit NULL.

**Comment by fhuberts** [comment]
The null test is there for a good reason:
when you specify a NULL argument then the corresponding value is NOT stored.

I inspected all invocations and everything is in order.

It's the same hazard as with printf, you have to use the function the right way, otherwise unexpected stuff will happen.
